### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by keerthivasanm** [mocks-server/core#151]
**Is your feature request related to a problem? Please describe.**
We have a bunch of mocks as `.ts` files for other tests and would like use them for `mocks-server`.

**Describe the solution you'd like**
Provide a way to configure node to use typescript.

**Comment by javierbrea** [comment]
Hi again @keerthivasanm,

I have already implemented it and now I'm preparing the new release. You can check how the solution will look like in this new section of the [pre-release docs](https://www.mocks-server.org/docs/next/guides-using-babel#typescript-example).

I hope to publish it during this week.

**Comment by keerthivasanm** [comment]
That was quick turnaround. Thanks @javierbrea. I'm waiting for the release :)
