### ISSUE TITLE
FilesLoader error shouldn't be masked

### ISSUE THREAD

**Issue by Palen** [mocks-server/core#96]
**Is your feature request related to a problem? Please describe.**
Errors like file imports or other stuff are masked because the exception is not passed to the logger.

**Describe the solution you'd like**
Change this line 
https://github.com/mocks-server/core/blob/9fc81905b92e329a7cbb4149c70edf191b32a9b9/src/plugins/FilesLoader.js#L120
By this one:
`this._tracer.error(``Error loading files from folder ${this._path} with error: ${error.message}``);`

**Comment by javierbrea** [comment]
Thanks @Palen! I think it would be even better to log the full error object to get the error stack trace:

```js
this._tracer.error(`Error loading files from folder ${this._path} with error: ${error.message}`, error);
```
